
analysis:
    input_data:         test_sim.uvh5
    coherent_avg:       True

# N.B. Make sure there is a dot when specifying numbers with scientific notation
redcal:
    filetype:           uvh5
    outdir:             
    clobber:            True 
    pol_mode:           1pol 
    gain:               0.4  
    min_bl_cut:         10.
    max_bl_cut:         40.

